name: Remove ZeroPoint branding when used as a template

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository != 'MWDelaney/ZeroPoint'
    steps:

      - name: Get current branch name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash
        id: getBranch

      - name: Get to the owner of this repository
        run: echo "::set-output name=owner::$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')"
        shell: bash
        id: getOwner

      - name: Get the repository name and convert it to lowercase
        run: echo "::set-output name=slug::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' '_' | tr '[:upper:]' '[:lower:]')"
        shell: bash
        id: getSlug

      - name: Get the repository name
        run: echo "::set-output name=name::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        shell: bash
        id: getName

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.getBranch.outputs.branch }}

      - name: Replace owner
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "MWDelaney"
          replace: ${{ steps.getOwner.outputs.owner }}
          regex: false

      - name: Replace repository slug
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "ZeroPoint"
          replace: ${{ steps.getSlug.outputs.slug }}
          regex: false

      - name: Replace repository name
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "zeropoint"
          replace: ${{ steps.getName.outputs.name }}
          regex: false

      - name: Archive template README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.md"
          target: "README.template.md"

      - name: Replace with project README.md
        uses: canastro/copy-file-action@master
        with:
          source: "README.ZeroPoint.md"
          target: "README.md"

      - name: Commit changes and delete this workflow
        uses: EndBug/add-and-commit@v7
        with:
          remove: '["./.github/workflows/zeropoint_template.yml", "./README.ZeroPoint.md"]'
          message: "Up to zero 🪐"
          tag: 'v1.0.0 --force'
